<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.water</groupId>
    <artifactId>Tiny-MQ</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>

    <modules>
        <module>mq-common</module>
        <module>mq-producer</module>
        <module>mq-consumer</module>
        <module>mq-test</module>
        <module>mq-broker</module>
    </modules>

    <properties>
        <!--============================== All Plugins START ==============================-->
        <plugin.compiler.version>3.2</plugin.compiler.version>
        <plugin.compiler.version>3.2</plugin.compiler.version>
        <plugin.surefire.version>2.18.1</plugin.surefire.version>
        <plugin.surefire.skip-it>false</plugin.surefire.skip-it>
        <plugin.surefire.ignore-failure>false</plugin.surefire.ignore-failure>

        <plugin.maven-source-plugin.version>2.2.1</plugin.maven-source-plugin.version>
        <plugin.maven-javadoc-plugin.version>2.9.1</plugin.maven-javadoc-plugin.version>
        <plugin.maven-gpg-plugin.version>1.5</plugin.maven-gpg-plugin.version>

        <!--============================== MAIN ==============================-->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.compiler.level>1.8</project.compiler.level>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>

        <!--============================== INTER ==============================-->
        <heaven.version>0.1.161</heaven.version>
        <log-integration.version>1.1.8</log-integration.version>
        <json.version>0.1.1</json.version>
        <load-balance.version>0.0.5</load-balance.version>

        <!--============================== OTHER ==============================-->
        <junit.version>4.12</junit.version>
        <netty.version>4.1.42.Final</netty.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!--============================== SELF ==============================-->
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>mq-producer</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>mq-consumer</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>mq-common</artifactId>
                <version>${project.version}</version>
            </dependency>
            <dependency>
                <groupId>${project.groupId}</groupId>
                <artifactId>mq-broker</artifactId>
                <version>${project.version}</version>
            </dependency>
            <!--============================== INTER ==============================-->
            <dependency>
                <groupId>com.github.houbb</groupId>
                <artifactId>id-core</artifactId>
                <version>0.0.6</version>
            </dependency>

            <dependency>
                <groupId>com.github.houbb</groupId>
                <artifactId>log-integration</artifactId>
                <version>${log-integration.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.houbb</groupId>
                <artifactId>heaven</artifactId>
                <version>${heaven.version}</version>
            </dependency>

            <dependency>
                <groupId>com.github.houbb</groupId>
                <artifactId>load-balance</artifactId>
                <version>${load-balance.version}</version>
            </dependency>

            <!--============================== OTHER ==============================-->
            <dependency>
                <groupId>junit</groupId>
                <artifactId>junit</artifactId>
                <version>${junit.version}</version>
                <scope>test</scope>
            </dependency>

            <dependency>
                <groupId>io.netty</groupId>
                <artifactId>netty-all</artifactId>
                <version>${netty.version}</version>
            </dependency>

            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>fastjson</artifactId>
                <version>1.2.76</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>